apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ffk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-hmsreg-gateway_ffk_no
      fintlabs.no/org-id: ffk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ffk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ffk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/ffk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/ffk-no/api/hmsreg/instances/sak"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/ffk-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/ffk-no/actuator/prometheus"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "ffk-no"
    target:
      kind: Application
      name: fint-flyt-hmsreg-gateway

