apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-hmsreg-gateway_vlfk_no
      fintlabs.no/org-id: vlfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/vlfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/vlfk-no/api/hmsreg/instances/sak"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/vlfk-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/vlfk-no/actuator/prometheus"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "vlfk-no"
    target:
      kind: Application
      name: fint-flyt-hmsreg-gateway

