apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-hmsreg-gateway_trondelagfylke_no
      fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelagfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/trondelagfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/trondelagfylke-no/api/hmsreg/instances/sak"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/trondelagfylke-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/trondelagfylke-no/actuator/prometheus"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "trondelagfylke-no"
    target:
      kind: Application
      name: fint-flyt-hmsreg-gateway

